### ISSUE TITLE
What are your thoughts about using pretrained embeddings like Glove?

### ISSUE THREAD

**Issue by prats226** [jagadeeshraja/quora_duplicate_detection#2]
https://github.com/jagadeeshraja/quora_duplicate_detection/blob/0730316f46a6b6bd520bbf01ff1429f3c857322f/src/deep_learning_duplicate_prediction.py#L42

**Comment by jagadeeshraja** [comment]
Actually it should help us do better, if we use them.. something worth evaluating is,  If we freeze the weights of glove as word embeddings or learn adaptively with just keeping glove as starting point, we can see which one gives us better results overall..

One major problem, I see with glove or word2vec is we may not get word embeddings for all words in our corpus... and sometimes, that may be deal breaker if we rely a lot on pre-trained vectors
